### ISSUE TITLE
El Cuento

### ISSUE THREAD

**Issue by ghost** [CKDark44n/fivetic-test#3]

**Comment by dhse1992** [comment]
Este es el cuento del grupo FiveTic
Las siete palabras para que cada compañero escoja dos y a partir de éstas forme un cuento:

Mar.
Arena.
Playa.
Luna.
Cielo.
Estrellas.
Viento.
Hola buen día compañeros, escojo cielo y estrellas para el cuento.

**Comment by dhse1992** [comment]
EL universo maravilla sin entender.

El universo... tan grande que ningún ser humano a ciencia cierta es capaz de dimensionar su tamaño, su fuerza y su conformación total. Desde que el ser humano existe, siempre se ha hecho las mismas preguntas:

Como conquistare el cielo?

Que tan enorme son las estrellas?

Tendremos vida en otros planetas?

Cuando podremos vivir fuera de los dominios de la tierra?

Nuestra obsesión por alcanzar lo que parece imposible, siempre pone a prueba nuestro conocimiento, nuestra capacidad de superación a si mismos, y la idea de que lo que parece inalcanzable en algún tiempo es posible, cada vez que miramos al cielo y vemos la majestuosidad de las estrellas, entramos en un encuentro existencial de cuan pequeños somos en el universo y en todo lo que nos rodea. pero al mismo tiempo vemos cuan grandes somos, no importa las dificultades que se nos presenten, con persistencia, dedicación, esfuerzo, sacrificio, seremos capaces de hacer lo que nos propongamos... hemos sido dotados, de grandes capacidades físicas y mentales, y el mismo universo nos pide que usemos todas aquellas capacidades con el fin de que algún día, en algún momento de nuestra historia, seamos recordados como una estrella mas en el cielo. en ese inmenso firmamento que tan majestuosamente día y noche nos abriga para mostrarnos, que somos valiosos, para todo aquel que nos rodea.

Siempre que mires al cielo y veas las estrellas al anochecer recuerda. Eres importante, eres valioso. estas disfrutando de las maravillas de lo creado y de lo que existe.

**Comment by dhse1992** [comment]
Este es el cuento del grupo FiveTic
Las siete palabras para que cada compañero escoja dos y a partir de éstas forme un cuento:

Mar.
Arena.
Playa.
Luna.
Cielo.
Estrellas.
Viento.

**Comment by CKDark44n** [comment]
> Este es el cuento del grupo FiveTic
> Las siete palabras para que cada compañero escoja dos y a partir de éstas forme un cuento:
> 
> Mar.
> Arena.
> Playa.
> Luna.
> Cielo.
> Estrellas.
> Viento.

Hola Diego, escojo cielo y estrellas Para el cuento

**Comment by CKDark44n** [comment]
EL universo maravilla sin entender.

El universo... tan grande que ningún ser humano a ciencia cierta es capaz de dimensionar su tamaño, su fuerza y su conformación total. Desde que el ser humano existe, siempre se ha hecho las mismas preguntas:

Como conquistare el cielo?

Que tan enorme son las estrellas?

Tendremos vida en otros planetas?

Cuando podremos vivir fuera de los dominios de la tierra?

Nuestra obsesión por alcanzar lo que parece imposible, siempre pone a prueba nuestro conocimiento, nuestra capacidad de superación a si mismos, y la idea de que lo que parece inalcanzable en algún tiempo es posible, cada vez que miramos al cielo y vemos la majestuosidad de las estrellas, entramos en un encuentro existencial de cuan pequeños somos en el universo y en todo lo que nos rodea. pero al mismo tiempo vemos cuan grandes somos, no importa las dificultades que se nos presenten, con persistencia, dedicación, esfuerzo, sacrificio, seremos capaces de hacer lo que nos propongamos... hemos sido dotados, de grandes capacidades físicas y mentales, y el mismo universo nos pide que usemos todas aquellas capacidades con el fin de que algún día, en algún momento de nuestra historia, seamos recordados como una estrella mas en el cielo. en ese inmenso firmamento que tan majestuosamente día y noche nos abriga para mostrarnos, que somos valiosos, para todo aquel que nos rodea.

Siempre que mires al cielo y veas las estrellas al anochecer recuerda. Eres importante, eres valioso. estas disfrutando de las maravillas de lo creado y de lo que existe.

**Comment by jaspe60** [comment]
Palabras elegidas Mar y Viento.

Y así es como decidido cambiar de actitud, no más quejas, no más lamentos…
Busco de manera profunda esa conexión con su propio ser, se empezó a mover por fe soltando por un momento la lógica, los métodos y las respuestas. Permitiendo que el viento se lleve todo y disfrutando de esa presencia en su ser sin preguntarse de donde viene o a donde va, solo abriendo su mente y siguiendo la dirección de este viento que le mostraba opciones tan grandes y llena de colores como el mar.

**Comment by dhse1992** [comment]
Que gran inspiración

**Comment by dhse1992** [comment]
Las piedras estaban en su camino, pero él era un ser con fuego dentro suyo, tenia alma valiente que nunca se daba  por vencida, quería cumplir sus sueños, también caminaba a través de una paisaje escarpado y lleno de recovecos, pero solo levantaba sus pies y saltando se elevaba como una pluma.

Siempre las piedras y el fuego eran elementos permanentes en su ratos en que volaba, y mientras disfrutaba de la gran vista desde las alturas, veía como la vida le arrojaba piedras, pero él ya no caería nunca más, porque ya había salido impulsado para siempre hacia la gran altura y plenitud de sus sueños, por el infinito e indestructible fuego que había en su interior.

**Comment by kike0290** [comment]
Playa y Luna

Luna vive en un pequeño pueblo que está muy lejos del mar, ella nunca lo ha visto, pero le gusta imaginar que va  a la playa a jugar en la arena y a nadar entre los peces.

Luna tiene 9 años, es muy divertida y tiene mucha imaginación. La primera vez que vio el mar, fue en una película donde un grupo de niños viajaban con sus padres y se pasaban el día jugando a la pelota y haciendo castillos de arena. Le gustó tanto que desde entonces, cada vez que tiene vacaciones en el colegio, le pide a sus padres que le lleven al mar. Pero todavía no han podido ir.

Sus padres trabajan mucho y nunca han podido cumplir el sueño de Luna, pero están deseando llevar a su pequeña hija a disfrutar del mar. Así que todos los años intentan hacer lo posible por planear unas vacaciones en la playa, pero siempre hay algo que se lo impide: excursiones con los primos y tíos de Luna, campamentos del colegio, o el trabajo de sus padres.

Pero Luna es muy comprensiva y sabe que algún día irán, pues sabe que sus padres la llevarán en cuanto tengan la oportunidad.

Afortunadamente para Luna, esa oportunidad llegaría antes de lo que esperaba.

Un día, cuando todavía faltaban dos semana para que acabara el colegio, sus padres fueron a recogerla a la salida con un cubo, una pala y un rastrillo de playa. Cuando Luna lo vio empezó a saltar y a gritar, arrancó el cubo de las manos de su padre y se lo puso el la cabeza como si fuera una armadura, y luego agarró la pala y el rastrillo y los alzó hacia el cielo a modo de trofeo. Por fin se iba a cumplir su sueño y rebosaba felicidad.

– “¡Vamos a ver el mar, vamos a ver el mar!” -gritaba, mientras sus amigos del cole la miraban sonriendo y la abrazaban, al saber que la pequeña iba a ver el mar.

Como todavía faltaban dos semanas para que empezaran las vacaciones de verano, Lola iba al colegio mientras sus padres organizaban el viaje, reservaban los billetes de avión, miraban los hoteles, planeaban las excursiones que iban a hacer… y algunos días a la salida del cole, se iban con Lola a comprar bañadores, una toalla playera, crema de sol, sombrilla, sandalias… todo lo necesario para que el viaje fuera perfecto para la pequeña Luna.

Las dos semanas pasaron rápido, y por fin llegó el día que Lola tanto ansiaba. Era el último día de colegio y en cuanto la clases terminaran, sus padres iban a ir a recogerla con las maletas hechas para ir directamente al aeropuerto.

Cuando Luna salió a la puerta del colegio y vio a sus padres a lo lejos, se despidió de sus amigos y corrió hacia ellos con la sonrisa más grande que jamás había iluminado su cara.

Cuando llegó al coche entró de un salto en la parte de atrás y gritó:

– “¡Rumbo al mar, por favor!”– Riendo

– “A sus órdenes pequeña sirena”– dijo su padre.

Y el coche se puso en marcha camino al aeropuerto, para coger el avión que les llevaría a la vacaciones de sus sueños.

**Comment by totti192** [comment]
Montaña y Arena

Érase una vez un simpático y risueño niño que se llamaba Pol. Sus padres que vivían en Barcelona se trasladaron a la isla de Tenerife por motivos de trabajo y allí nació él entre el amarillo de la playa, el rojo de la montaña y el azul del mar. Una calurosa tarde de verano, mientras Pol jugaba con su cubo en  la arena de la playa, muy cerca de la Montaña Roja, su osito de peluche favorito se perdió. Nadie se dio cuenta hasta que al llegar la noche Pol, que después de escuchar un cuento siempre se dormía abrazado a su osito, echó de menos a su compañero de sueños. Se puso muy triste y empezó a llorar. Su mamá angustiada por el llanto del pequeño regresó a la playa. Buscó, buscó y buscó pero el osito no apareció.

Fatigado por el llanto y la tristeza Pol se durmió al fin. A la mañana siguiente su mamá  volvió a la playa para buscar el osito. Allí se encontró  con el caluroso y luminoso sol, el fuerte y poderoso viento y las altas y ruidosas olas.

–       Querido y luminoso Sol-  preguntó la mamá al astro Rey- ¿has visto el osito de peluche de Pol?

El astro Rey iluminó la playa con sus potentes rayos, pero ni rastro del peluche

Y siguió caminando y preguntando

–       Querido y poderoso viento- preguntó la mamá – ¿has visto el osito de peluche de Pol?

El fuerte viento de El Médano sopló con más fuerza que nunca sobre la arena levantando con él miles y miles de objetos enterrados. Había monedas, anillos, restos de comida y hasta colillas, pero ni rastro del peluche.

Y siguió caminando y preguntando

–       Queridas y ruidosas olas- volvió a preguntar la mamá- ¿han visto el osito de peluche de Pol?

Las altas y ruidosas olas posaron en la arena miles y miles  de objetos lanzados al mar. Había cáscaras de plátano, restos de botellas de plástico y algas, pero ni rastro del peluche.

Y siguió caminando buscando a quién preguntar.

Cansada de tanto caminar y preguntar se sentó en la orilla del mar para pensar con más claridad. Pronto se hizo de noche y la luna llena apareció en el cielo.

–       ¿Qué te pasa?- preguntó la luna a la mamá de Pol- ¿porqué estás triste?

–       Pol ha perdido su osito de peluche y con él su eterna sonrisa; si no lo encuentro pronto temo que no vuelva a sonreír jamás – contestó la mamá con voz temblorosa.

–       Si preguntas a la primera estrella de la noche, la más observadora e inteligente, seguro que te dará la respuesta que buscas- le recomendó la luna llena.

La mamá de Pol miró el cielo cuajadito de estrellas tratando de averiguar cuál de ellas sería la primera estrella de esa noche tan estrellada. ¡Qué difícil misión!- pensó la mamá.  La luna llena volvió a su encuentro para ayudarla. Con su potente luz iluminó una gran ola que  escondía entre la espesura de su espuma una estrella. Era la  primera estrella de la noche. Se había convertido en una estrella de mar para bajar a tierra firme  y ayudar a la mamá a encontrar el osito. La tarde anterior, apenas unos segundos después de ponerse el sol y ocupar su lugar en el cielo estrellado, había visto cómo un pequeño caballito de mar arrastraba por la arena de la playa el osito de Pol dejando un camino dibujado a su paso. No tuvieron más que seguir el dorado camino. Pronto dieron con el escondite del caballito. En lo más alto de una rocosa roca estaba el osito. Sucio y mojado. Salitre en los ojos y rasguños en la panza. ¡Pobre osito!

 No oyó el caballito de mar, camuflado en la roca, la llegada de los intrusos.  Su rizada cola enrollada alrededor del osito delató su presencia. Al verse descubierto les contó lo sucedido.

–       Cada tarde- comenzó a explicar el caballito- desde mi escondite secreto,  observaba a  Pol jugar en la arena con su cubo y su pala. Lo veía feliz haciendo castillos que adornaba con conchas y caracolas y pensé que no echaría de menos a su osito.

–       Sin que nadie me viera- continuó hablando el caballito- me camuflé con la arena y me acerqué a la bolsa donde estaba el osito. Lo enrollé en mi cola y lo arrastré hasta esta roca. Sólo quería tener un compañero de juegos. Estoy muy solo viviendo en este océano tan lejos de mi casa. Los caballitos de mar estamos en peligro de extinción y no me quedan amigos para jugar.

La mamá y la estrella miraron al caballito sin creer aún que en el mundo marino hubiera alguien tan pequeño y sin embargo tan valiente. Durante unos minutos todos permanecieron en silencio. Sólo se escuchaba el sonoro oleaje.

 La mamá de Pol, feliz por haber encontrado el osito, no se enfadó mucho con el caballito que le prometió no volver a coger lo que no era suyo y pedirle perdón a Pol.

Así fue como Pol recuperó la sonrisa que compartió con dos nuevos compañeros de juego: el caballito y la estrella de mar.

**Comment by dhse22** [comment]
Este es el cuento del grupo FiveTic
Las siete palabras para que cada compañero escoja dos y a partir de éstas forme un cuento:
Mar.
Arena.
Playa.
Luna.
Cielo.
Estrellas.
Viento.
Piedras.
Fuego.
Montaña.
Las asignaciones de las palabras son:
Miguel Rodríguez: Cielo y Estrellas.
Ana Milena Muñóz: Mar y Viento.
Diego Hernán Saavedra Espejo: Piedras y Fuego.
José Contreras: Montaña y Arena.

**Comment by dhse22** [comment]
Las piedras estaban en su camino, pero él era un ser con fuego dentro suyo, tenia alma valiente que nunca se daba por vencida, quería cumplir sus sueños, también caminaba a través de una paisaje escarpado y lleno de recovecos, pero solo levantaba sus pies y saltando se elevaba como una pluma.
Siempre las piedras y el fuego eran elementos permanentes en su ratos en que volaba, y mientras disfrutaba de la gran vista desde las alturas, veía como la vida le arrojaba piedras, pero él ya no caería nunca más, porque ya había salido impulsado para siempre hacia la gran altura y plenitud de sus sueños, por el infinito e indestructible fuego que había en su interior.
En este libro de cuentos y relatos la autora nos propone un viaje al interior de ella misma, describiendo con una sensibilidad especial los fenómenos de la naturaleza a los que describe desde sus emociones. Esa visión le permite transformar su prosa, en poesía sin métrica. El entorno que la rodea es la Patagonia y en especial el Balneario el Cóndor (Río Negro) su lugar en el mundo y su lecho eterno.
En este libro de cuentos y relatos la autora nos propone un viaje al interior de ella misma, describiendo con una sensibilidad especial los fenómenos de la naturaleza a los que describe desde sus emociones. Esa visión le permite transformar su prosa, en poesía sin métrica. El entorno que la rodea es la Patagonia y en especial el Balneario el Cóndor (Río Negro) su lugar en el mundo y su lecho eterno.
Siempre las piedras y el fuego eran elementos permanentes en su ratos en que volaba, y mientras disfrutaba de la gran vista desde las alturas, veía como la vida le arrojaba piedras, pero él ya no caería nunca más, porque ya había salido impulsado para siempre hacia la gran altura y plenitud de sus sueños, por el infinito e indestructible fuego que había en su interior.
